//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpendingTracker_API.Resources.Pages.Index {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IndexPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndexPageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpendingTracker_API.Resources.Pages.Index.IndexPageResources", typeof(IndexPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User authentication and authorization via JWT.
        /// </summary>
        public static string AuthenticationFeature {
            get {
                return ResourceManager.GetString("AuthenticationFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This server supports both Android and web applications..
        /// </summary>
        public static string ClientSupport {
            get {
                return ResourceManager.GetString("ClientSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomeImgTitle {
            get {
                return ResourceManager.GetString("HomeImgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implemented Features.
        /// </summary>
        public static string ImplementedFeatures {
            get {
                return ResourceManager.GetString("ImplementedFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginImgTitle {
            get {
                return ResourceManager.GetString("LoginImgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Snapshots.
        /// </summary>
        public static string MobileSnapshot {
            get {
                return ResourceManager.GetString("MobileSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a nice day.
        /// </summary>
        public static string NiceDay {
            get {
                return ResourceManager.GetString("NiceDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsImgTitle {
            get {
                return ResourceManager.GetString("SettingsImgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string StatisticsImgTitle {
            get {
                return ResourceManager.GetString("StatisticsImgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Web App.
        /// </summary>
        public static string ToWeb {
            get {
                return ResourceManager.GetString("ToWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions with Add button.
        /// </summary>
        public static string TransactionAddImgTitle {
            get {
                return ResourceManager.GetString("TransactionAddImgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRUD operations for transaction tracking.
        /// </summary>
        public static string TransactionCrudFeature {
            get {
                return ResourceManager.GetString("TransactionCrudFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction details.
        /// </summary>
        public static string TransactionDetailsImgTitle {
            get {
                return ResourceManager.GetString("TransactionDetailsImgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string TransactionsImgTitle {
            get {
                return ResourceManager.GetString("TransactionsImgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Money Diary.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app was previously named Spending Tracker, hence you&apos;ll see this name in some parts of the app that is not yet updated..
        /// </summary>
        public static string WelcomeSmallSubtitle {
            get {
                return ResourceManager.GetString("WelcomeSmallSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is Money Diary, an app to help you track your income and spending, created by.
        /// </summary>
        public static string WelcomeSubtitle {
            get {
                return ResourceManager.GetString("WelcomeSubtitle", resourceCulture);
            }
        }
    }
}
